---
- name: APT install packages
  become: yes
  apt: name={{ item }} state=latest update_cache=true
  with_items:
    - git
    - python3
    - python3-dev
    - python3-pip
    - redis-server

- name: Install pip packages
  become: yes
  pip: name={{ item }} state=latest executable=pip3
  with_items:
    - virtualenv
    - pip

- name: Install python project
  pip:
    requirements: "{{ project_path }}/backend/requirements.txt"
    virtualenv: "{{ venv_path }}"
    virtualenv_python: python3

# - name: Run migrations TODO: uncomment it
#   django_manage:
#     command: migrate --noinput
#     app_path: "{{ project_path }}/backend"
#     virtualenv: "{{ venv_path }}"
#   environment: "{{ django_env }}"
